<?php /** @var $this \MvcCore\View */ ?><!DOCTYPE HTML>
<html lang="en-US">
	<head>
		<meta charset="UTF-8" />
		<title><?php echo $this->title; ?></title>
		
		<?php /* force render mode in newest IE, strictly do not use any back compatibility modes in MSIE browsers for this page */ ?>
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		
		<link rel="shortcut icon" href="static/img/favicon.ico" />
		<?php echo $this->Css('fixedHead')->Render(); ?>
		<?php echo $this->Js('fixedHead')->Render(); ?>
	</head>
	<body>
	
		<!--[if lt IE 9]><div class="old-browser-warning"><p>Your browser is <b>very</b> old. <br />Please install any actual browser, for example <br /><a href="https://www.google.com/chrome" target="_blank">Google Chrome</a>, <a href="https://www.apple.com/safari" target="_blank">Apple Safari</a> or <a href="https://www.mozilla.org/en/firefox/new" target="_blank">Mozilla Firefox</a>.</p></div><![endif]-->
			
		<div class="master-container">
			<div class="content">

				<?php echo $this->horizontalNav->Render('navigation-horizontal'); ?>
				
				<?php echo $this->GetContent(); ?>
					
				<hr />
				<?php echo $this->Url('Front\Sitemap:Index', ['localization' => $this->localization]); ?><br />
				<?php echo $this->Url('Admin\Index:Index', ['localization' => $this->localization]); ?><br />
				<?php echo $this->Url('Admin\Index:Index'); ?><br />
				<?php echo $this->mediaSiteVersion; ?><br />
				<br />

				<?php if ($this->redirectedSourceUrl): ?>
					<a href="<?php echo $this->redirectedSourceUrl; ?>">
						Go back to source url
					</a>
				<?php endif; ?>

			</div>
			<?php echo $this->RenderLayout('front/footer.media-navigation'); ?>
			<?php echo $this->RenderLayout('front/footer.localization-navigation'); ?>
		</div>
		
	</body>
	
	<?php echo $this->Js('varFoot')->Render(); ?>
	
</html>
